fix(types): export WritableStreamLike
Exposing this avoids a potential problem for modules re-exporting `Loggerr`:

```
error TS9006: Declaration emit for this file requires using private name WritableStreamLike from module /path/to/node_modules/loggerr/index. An explicit type annotation may unblock declaration emit.
```